version: "3.3"
services:
  app:
    build:
      context: ./
    ports:
      - "8080:8080"
    networks:
      - internal
    environment:
      - spring.security.oauth2.client.provider.okta.issuer-uri=$OKTA_DOMAIN_URL
      - spring.security.oauth2.client.registration.okta.client-id=$CLIENT_ID
      - spring.security.oauth2.client.registration.okta.client-secret=$CLIENT_SECRET

networks:
  internal: