spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            issuer-uri:
        registration:
          okta:
            client-id:
            client-secret:

springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/swagger-ui.html
    disable-swagger-default-url: true