spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            issuer-uri: https://dev-1960310.okta.com/oauth2/default
        registration:
          okta:
            client-id:
            client-secret: 